### ISSUE TITLE
Value error for Dirichlet distribution

### ISSUE THREAD

**Issue by noman-bashir** [LINs-lab/FedBR#1]
Hi, thank you for sharing the code. I am facing a problem running the code with CIFAR10 or MNIST dataset. I have not tried the other datasets. 

```
python3 -m fedbr.scripts.train_fed   --data_dir=./fedbr/data/CIFAR10/   --algorithm FedBR   --dataset RotatedCIFAR10   --train_envs 10   --steps 50000   --output_dir output-cifar10/FedBR   --local_steps 50   --device 6   --save_model_e
very_checkpoint   --seed 12345

WARNING:root:The WILDS package is out of date. Your version is 1.2.2, while the latest version is 2.0.0.

Environment:
        Python: 3.9.2
        PyTorch: 2.0.1+cu117
        Torchvision: 0.15.2+cu117
        CUDA: 11.7
        CUDNN: 8500
        NumPy: 1.20.3
        PIL: 10.0.0
Args:
        algorithm: FedBR
        checkpoint_freq: None
        data_dir: ./fedbr/data/CIFAR10/
        dataset: RotatedCIFAR10
        device: 6
        fedmix_lambda: 0.1
        holdout_fraction: 0.2
        hparams: None
        hparams_seed: 0
        local_steps: 50
        output_dir: output-cifar10/FedBR
        save_model_every_checkpoint: True
        seed: 12345
        skip_model_save: False
        steps: 50000
        task: domain_generalization
        train_envs: 10
        trial_seed: 0
        uda_holdout_fraction: 0
        use_Mixture: False
        use_Mixup: False
        virtual_set: style_GAN_init_28_c100_200
HParams:
        batch_size: 32
        class_balanced: False
        data_augmentation: True
        lr: 0.01
        nonlinear_classifier: False
        resnet18: False
        resnet_dropout: 0.0
        weight_decay: 0.0
device: 6

Files already downloaded and verified
Files already downloaded and verified

/home/userX/FedBR/fedbr/datasets.py:330: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  clients_images[i] = torch.tensor([image for image in clients_images[i]])
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/userX/FedBR/fedbr/scripts/train_fed.py", line 170, in <module>
    dataset = vars(datasets)[args.dataset](args.data_dir,
  File "/home/userX/FedBR/fedbr/datasets.py", line 411, in __init__
    super(RotatedCIFAR10, self).__init__(root, [0] * train_envs + [0, 15, 30, 45, 60, 75, 90, 105, 120, 135],
  File "/home/userX/FedBR/fedbr/datasets.py", line 386, in __init__
    clients_images, clients_labels = self.get_noniid_class_and_labels(original_images_tr, original_labels_tr, len(environments) - 10)
  File "/home/userX/FedBR/fedbr/datasets.py", line 316, in get_noniid_class_and_labels
    q = dirichlet.Dirichlet(0.1 * p).sample()
  File "/home/userX/.local/lib/python3.9/site-packages/torch/distributions/dirichlet.py", line 54, in __init__
    super().__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/home/userX/.local/lib/python3.9/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter concentration (Tensor of shape (10,)) of distribution Dirichlet(concentration: torch.Size([10])) to satisfy the constraint IndependentConstraint(GreaterThan(lower_bound=0.0), 1), but found invalid values:
tensor([0.0111, 0.0111, 0.0111, 0.0111, 0.0000, 0.0111, 0.0111, 0.0111, 0.0111,
        0.0111])
```

The value of 0 in the tensor is causing the problem. How can I solve this?

**Comment by gyxxyg** [comment]
The most recent version of the torch prevents initializing "Dirichlet" objects with zero, which results in this error. To fix this issue, you can try to reinstall the torch==1.7.1.
